name: Jest Tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Tests start
              if: github.event_name != 'push'
              uses: mshick/add-pr-comment@v2
              continue-on-error: true
              with:
                  message-id: jest-tests
                  message: |
                      ### <span aria-hidden="true">ğŸš§</span> Running tests...

            - name: Test using Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - run: yarn install
            - name: Get number of CPU cores
              id: cpu-cores
              uses: SimenB/github-actions-cpu-cores@v1
            - name: run tests
              run: yarn test:ci --max-workers ${{ steps.cpu-cores.outputs.count }}

            - name: Tests Passed âœ…
              if: ${{ success() }}
              run: |
                  curl --request POST \
                  --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                    "context": "tests",
                    "state": "success",
                    "description": "Tests passed",
                    "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }'

            - name: Tests Failed âŒ
              if: ${{ failure() }}
              run: |
                  curl --request POST \
                  --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
                  --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                    "context": "tests",
                    "state": "failure",
                    "description": "Tests failed",
                    "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }'

            - name: Add PR Comment
              uses: mshick/add-pr-comment@v2
              with:
                  message-id: jest-tests
                  message-success: |
                      ### <span aria-hidden="true">âœ…</span> Jest Tests Successful!

                      |  Name | Link |
                      |---------------------------------|------------------------|
                      |<span aria-hidden="true">ğŸ”¨</span> Latest commit | ${{ github.sha }} |
                      |<span aria-hidden="true">ğŸ”</span> Latest test logs | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
                      ---
                  message-failure: |
                      ### <span aria-hidden="true">âŒ</span> Jest Tests Failed

                      |  Name | Link |
                      |---------------------------------|------------------------|
                      |<span aria-hidden="true">ğŸ”¨</span> Latest commit | ${{ github.sha }} |
                      |<span aria-hidden="true">ğŸ”</span> Latest test logs | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
                      ---
                  message-cancelled: |
                      âš  Jest Tests Cancelled
